spring:
    datasource:
        password: 123456
        url: jdbc:postgresql://localhost:5432/patient_db
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
    application:
        name: patient-service
    config:
        import: optional:configserver:http://localhost:8888
